### ISSUE TITLE
[question] send frames from unity3d to the SimpleDALPlugin

### ISSUE THREAD

**Issue by bomanden** [seanchas116/SimpleDALPlugin#4]
Hi interesting project, 
Would it be possible to integrate your SimpleDALPlugin with unity3d ? 
How to send frames SimpleDALPlugin.

**Comment by PhilippMatthes** [comment]
Maybe, as an entrypoint, you could use the Unity scripting API to obtain the virtual webcam as a texture:

https://docs.unity3d.com/ScriptReference/WebCamTexture.html

**Comment by seanchas116** [comment]
The Windows version of it (https://github.com/schellingb/UnityCapture) would be a good reference.
UnityCapture consists of a Windows virtual camera implementation and a Unity plugin that sends frames to the virtual camera via a memory-mapped file.
The same mechanism could be used (create a Unity plugin that captures frames of Unity cameras and send it to SimpleDALPlugin-derived virtual camera implementation via IPC).

**Comment by xocialize** [comment]
Do you have a suggested IPC?  I’m looking into doing something similar and was considering https://github.com/swiftsocket/SwiftSocket 

This is my first try at IPC and I haven’t gotten started so I’d be very open to suggestion.

**Comment by PhilippMatthes** [comment]
@seanchas116 I think you can close this issue, due to nobody having contributed to this discussion for almost 30 days.

**Comment by Raj123456788** [comment]
Folks, can someone please answer my question?
